### ISSUE TITLE
LbChiper compile error for iOS64

### ISSUE THREAD

**Issue by claudio-piffer** [TurboPack-Tokyo/LockBox#1]
Hi Roman,

I have a problem when try to compile LockBox for iOS64. The error is in the LbChiper.pas unit:

[DCC Error] LbCipher.pas(2071): E2581 Backend error: Function return type does not match operand type of return inst!  ret void i64Function return type does not match operand type of return inst!  ret void i64

All the other platforms are ok!

Thank you very much for your support!

Claudio

**Comment by claudio-piffer** [comment]
Hi Roman

in row 84 of the unit LbChiper.pas I changed

TRDLVector = record

in 

TRDLVector = packed record

With this little change now compile fine in iOS 64
I do some tests and let you know if everything is ok

Thank you very much

**Comment by romankassebaum** [comment]
Fixed.
